### ISSUE TITLE
Enable embedding of YouTube videos

### ISSUE THREAD

**Issue by annarciaga** [withMeaning/read#10]

**Comment by DonSqualo** [comment]
Embedding videos works natively, just make sure to use the actual embed link:

Not:
https://www.youtube.com/watch?v=uEb4qwzOXsU&ab_channel=MSNBC
But
https://www.youtube.com/embed/uEb4qwzOXsU

**Comment by annarciaga** [comment]
Tested it and it works. Thanks!
